
logging:
  level:
    root: INFO
    market: INFO
  file:
    name: market
    path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/online_telephone_market
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: messages
app:
  image:
    bucket: D:\JAVA\telephone_market\images
  #gpt:
  #  key: ${API_KEY_GPT}
   # api: ${API_GPT}
   # version: ${VERSION_GPT}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
